#!/bin/bash

echo "What is your name?"
read name

echo "Hello, $name!"






#!/bin/bash

echo "Enter the filename to check:"
read filename

if [ -e $filename ]; then
  echo "The file $filename exists in the current directory."
else
  echo "The file $filename does not exist in the current directory."
fi








#!/bin/bash

echo "Please enter a number:"
read num

if [ $num -eq 1 ]; then
  echo "You entered one!"
elif [ $num -eq 2 ]; then
  echo "You entered two!"
elif [ $num -eq 3 ]; then
  echo "You entered three!"
else
  echo "You entered a number other than 1, 2 or 3."
fi





